### PR TITLE
Change Fence Gate sound def to match latest MT 5.7

### LINKED ISSUE #2: Fence gates should not use "sound" key in node definition - By jwmhjwmh
This causes an error at load time after https://github.com/minetest/minetest/commit/525fc3833c40dcca478719533a87bc7b5e285e4e.

Minetest Game seems to use the key "_gate_sound" instead now.

### PR DESCRIPTION
**Pull request by ExeVirus**
I believe this merge should not be merged until next 5.7 release of Minetest because I think 5.6.1 won't be able to load it. Can't test with this machine.

(Merge from latest MTG master)

Closes #2

### CODE REVIEW

**Comment by MeseCraft** [comment]
Latest changes are supposed to target the unstable branch.

**Comment by ExeVirus** [comment]
Ah, my mistake, wasn't aware of the unstable branch. Will retarget PR when
I get to a PC

**Comment by ExeVirus** [comment]
Corrected, targeted at unstable now.

**Comment by MeseCraft** [comment]
merged, thanks exevirus!

**Pull request merged**
