### PR TITLE
Add light to magic items

### PR DESCRIPTION
**Pull request by AndyIII**
This takes a crack at adding light to the remaining magic items. The tomes, staves, and materials all have consistent lighting now, based on how the inventory image looks. This also makes februm crystal glow (since the inventory image shows it) but not februm blocks. The ore glows slightly in stone, but not enough to see other things by.

### CODE REVIEW

**Comment by MeseCraft** [comment]
Cool idea! to make the crystals glow. However, you can target unstable instead?

**Comment by AndyIII** [comment]
Oops I missed that. I'll see if I can change it somehow.

**Comment by MeseCraft** [comment]
Looks like you did it. Thank you. I'll review the PR.

**Comment by MeseCraft** [comment]
Looks good. Andy, I really appreciate the help and commits you've been doing, it means a lot to me to see commits coming through for MeseCraft. Feel free to join us at Mesecraft.com  as well.

**Pull request merged**
